
export const CONFIG = {
    MAX_RECOMMENDED_PRODUCTS: Number(process.env.RECOMMENDED_PRODUCTS_MAX_SIZE),
    MAX_PRODUCTS_PER_CATEGORY: Number(process.env.MAX_PRODUCTS_PER_CATEGORY),
    LAST_MONTHS_PRODUCTS_IN_ORDER: Number(process.env.LAST_MONTHS_PRODUCTS_IN_ORDER),
    MAX_BESTSELLS_PRODUCTS: Number(process.env.MAX_BESTSELLS_PRODUCTS),
    SCORES_MAX_SIZE: Number(process.env.SCORES_MAX_SIZE),
    BASE_PRODUCT_COMMENTS_COUNT: Number(process.env.BASE_PRODUCT_COMMENTS_COUNT),
    MAX_SEARCH_RESULT: Number(process.env.MAX_SEARCH_RESULT),
    DAYS_OF_SEARCH_NEXT_HOTSELL: Number(process.env.DAYS_OF_SEARCH_NEXT_HOTSELL)
}