
export const CONFIG = {
    MAX_RECOMMENDED_PRODUCTS: Number(process.env.RECOMMENDED_PRODUCTS_MAX_SIZE),
    MAX_PRODUCTS_PER_CATEGORY: Number(process.env.MAX_PRODUCTS_PER_CATEGORY),
    LAST_MONTHS_PRODUCTS_IN_ORDER: Number(process.env.LAST_MONTHS_PRODUCTS_IN_ORDER),
    MAX_BESTSELLS_PRODUCTS: Number(process.env.MAX_BESTSELLS_PRODUCTS),
    HITS_OF_WEEK_DAYS_PERIOD: Number(process.env.HITS_OF_WEEK_DAYS_PERIOD)
}