
export const CONFIG = {
    MAX_RECOMMENDED_PRODUCTS: Number(process.env.RECOMMENDED_PRODUCTS_MAX_SIZE),
    MAX_PRODUCTS_PER_CATEGORY: Number(process.env.MAX_PRODUCTS_PER_CATEGORY),
    ADV_FROM_MONTHS_PRIOR_TO_TODAY: Number(process.env.ADV_FROM_MONTHS_PRIOR_TO_TODAY)
}